var interpretation = {
	spades : {
		'1' : {
			name : '♣ 1',
			north : {text:'value north spades 1'},
			west : {text:'value west spades 1'},
			station : {text:'value station spades 1'},
			east : {text:'value east spades 1'},
			south : {text:'value south spades 1'},
		},
		'2' : {
			name : '♣ 2',
			north : {text:'value north spades 2'},
			west : {text:'value west spades 2'},
			station : {text:'value station spades 2'},
			east : {text:'value east spades 2'},
			south : {text:'value south spades 2'},
		},
		'3' : {
			name : '♣ 3',
			north : {text:'value north spades 3'},
			west : {text:'value west spades 3'},
			station : {text:'value station spades 3'},
			east : {text:'value east spades 3'},
			south : {text:'value south spades 3'},
		},
		'4' : {
			name : '♣ 4',
			north : {text:'value north spades 4'},
			west : {text:'value west spades 4'},
			station : {text:'value station spades 4'},
			east : {text:'value east spades 4'},
			south : {text:'value south spades 4'},
		},
		'5' : {
			name : '♣ 5',
			north : {text:'value north spades 5'},
			west : {text:'value west spades 5'},
			station : {text:'value station spades 5'},
			east : {text:'value east spades 5'},
			south : {text:'value south spades 5'},
		},
		'6' : {
			name : '♣ 6',
			north : {text:'value north spades 6'},
			west : {text:'value west spades 6'},
			station : {text:'value station spades 6'},
			east : {text:'value east spades 6'},
			south : {text:'value south spades 6'},
		},
		'7' : {
			name : '♣ 7',
			north : {text:'value north spades 7'},
			west : {text:'value west spades 7'},
			station : {text:'value station spades 7'},
			east : {text:'value east spades 7'},
			south : {text:'value south spades 7'},
		},
		'8' : {
			name : '♣ 8',
			north : {text:'value north spades 8'},
			west : {text:'value west spades 8'},
			station : {text:'value station spades 8'},
			east : {text:'value east spades 8'},
			south : {text:'value south spades 8'},
		},
		'9' : {
			name : '♣ 9',
			north : {text:'value north spades 9'},
			west : {text:'value west spades 9'},
			station : {text:'value station spades 9'},
			east : {text:'value east spades 9'},
			south : {text:'value south spades 9'},
		},
		'10' : {
			name : '♣ 10',
			north : {text:'value north spades 10'},
			west : {text:'value west spades 10'},
			station : {text:'value station spades 10'},
			east : {text:'value east spades 10'},
			south : {text:'value south spades 10'},
		},
		'11' : {
			name : '♣ J 11',
			north : {text:'value north spades J 11'},
			west : {text:'value west spades J 11'},
			station : {text:'value station spades J 11'},
			east : {text:'value east spades J 11'},
			south : {text:'value south spades J 11'},
		},
		'12' : {
			name : '♣ Q 12',
			north : {text:'value north spades Q 12'},
			west : {text:'value west spades Q 12'},
			station : {text:'value station spades Q 12'},
			east : {text:'value east spades Q 12'},
			south : {text:'value south spades Q 12'},
		},
		'13' : {
			name : '♣ K 13',
			north : {text:'value north spades K 13'},
			west : {text:'value west spades K 13'},
			station : {text:'value station spades K 13'},
			east : {text:'value east spades K 13'},
			south : {text:'value south spades K 13'},
		}
	},
	diamonds : {
		'1' : {
			name : '♦ 1',
			north : {text:'value north diamonds 1'},
			west : {text:'value west diamonds 1'},
			station : {text:'value station diamonds 1'},
			east : {text:'value east diamonds 1'},
			south : {text:'value south diamonds 1'},
		},
		'2' : {
			name : '♦ 2',
			north : {text:'value north diamonds 2'},
			west : {text:'value west diamonds 2'},
			station : {text:'value station diamonds 2'},
			east : {text:'value east diamonds 2'},
			south : {text:'value south diamonds 2'},
		},
		'3' : {
			name : '♦ 3',
			north : {text:'value north diamonds 3'},
			west : {text:'value west diamonds 3'},
			station : {text:'value station diamonds 3'},
			east : {text:'value east diamonds 3'},
			south : {text:'value south diamonds 3'},
		},
		'4' : {
			name : '♦ 4',
			north : {text:'value north diamonds 4'},
			west : {text:'value west diamonds 4'},
			station : {text:'value station diamonds 4'},
			east : {text:'value east diamonds 4'},
			south : {text:'value south diamonds 4'},
		},
		'5' : {
			name : '♦ 5',
			north : {text:'value north diamonds 5'},
			west : {text:'value west diamonds 5'},
			station : {text:'value station diamonds 5'},
			east : {text:'value east diamonds 5'},
			south : {text:'value south diamonds 5'},
		},
		'6' : {
			name : '♦ 6',
			north : {text:'value north diamonds 6'},
			west : {text:'value west diamonds 6'},
			station : {text:'value station diamonds 6'},
			east : {text:'value east diamonds 6'},
			south : {text:'value south diamonds 6'},
		},
		'7' : {
			name : '♦ 7',
			north : {text:'value north diamonds 7'},
			west : {text:'value west diamonds 7'},
			station : {text:'value station diamonds 7'},
			east : {text:'value east diamonds 7'},
			south : {text:'value south diamonds 7'},
		},
		'8' : {
			name : '♦ 8',
			north : {text:'value north diamonds 8'},
			west : {text:'value west diamonds 8'},
			station : {text:'value station diamonds 8'},
			east : {text:'value east diamonds 8'},
			south : {text:'value south diamonds 8'},
		},
		'9' : {
			name : '♦ 9',
			north : {text:'value north diamonds 9'},
			west : {text:'value west diamonds 9'},
			station : {text:'value station diamonds 9'},
			east : {text:'value east diamonds 9'},
			south : {text:'value south diamonds 9'},
		},
		'10' : {
			name : '♦ 10',
			north : {text:'value north diamonds 10'},
			west : {text:'value west diamonds 10'},
			station : {text:'value station diamonds 10'},
			east : {text:'value east diamonds 10'},
			south : {text:'value south diamonds 10'},
		},
		'11' : {
			name : '♦ J 11',
			north : {text:'value north diamonds J 11'},
			west : {text:'value west diamonds J 11'},
			station : {text:'value station diamonds J 11'},
			east : {text:'value east diamonds J 11'},
			south : {text:'value south diamonds J 11'},
		},
		'12' : {
			name : '♦ Q 12',
			north : {text:'value north diamonds Q 12'},
			west : {text:'value west diamonds Q 12'},
			station : {text:'value station diamonds Q 12'},
			east : {text:'value east diamonds Q 12'},
			south : {text:'value south diamonds Q 12'},
		},
		'13' : {
			name : '♦ K 13',
			north : {text:'value north diamonds K 13'},
			west : {text:'value west diamonds K 13'},
			station : {text:'value station diamonds K 13'},
			east : {text:'value east diamonds K 13'},
			south : {text:'value south diamonds K 13'},
		}
	},
	hearts : {
		'1' : {
			name : '♥ 1',
			north : {text:'value north hearts 1'},
			west : {text:'value west hearts 1'},
			station : {text:'value station hearts 1'},
			east : {text:'value east hearts 1'},
			south : {text:'value south hearts 1'},
		},
		'2' : {
			name : '♥ 2',
			north : {text:'value north hearts 2'},
			west : {text:'value west hearts 2'},
			station : {text:'value station hearts 2'},
			east : {text:'value east hearts 2'},
			south : {text:'value south hearts 2'},
		},
		'3' : {
			name : '♥ 3',
			north : {text:'value north hearts 3'},
			west : {text:'value west hearts 3'},
			station : {text:'value station hearts 3'},
			east : {text:'value east hearts 3'},
			south : {text:'value south hearts 3'},
		},
		'4' : {
			name : '♥ 4',
			north : {text:'value north hearts 4'},
			west : {text:'value west hearts 4'},
			station : {text:'value station hearts 4'},
			east : {text:'value east hearts 4'},
			south : {text:'value south hearts 4'},
		},
		'5' : {
			name : '♥ 5',
			north : {text:'value north hearts 5'},
			west : {text:'value west hearts 5'},
			station : {text:'value station hearts 5'},
			east : {text:'value east hearts 5'},
			south : {text:'value south hearts 5'},
		},
		'6' : {
			name : '♥ 6',
			north : {text:'value north hearts 6'},
			west : {text:'value west hearts 6'},
			station : {text:'value station hearts 6'},
			east : {text:'value east hearts 6'},
			south : {text:'value south hearts 6'},
		},
		'7' : {
			name : '♥ 7',
			north : {text:'value north hearts 7'},
			west : {text:'value west hearts 7'},
			station : {text:'value station hearts 7'},
			east : {text:'value east hearts 7'},
			south : {text:'value south hearts 7'},
		},
		'8' : {
			name : '♥ 8',
			north : {text:'value north hearts 8'},
			west : {text:'value west hearts 8'},
			station : {text:'value station hearts 8'},
			east : {text:'value east hearts 8'},
			south : {text:'value south hearts 8'},
		},
		'9' : {
			name : '♥ 9',
			north : {text:'value north hearts 9'},
			west : {text:'value west hearts 9'},
			station : {text:'value station hearts 9'},
			east : {text:'value east hearts 9'},
			south : {text:'value south hearts 9'},
		},
		'10' : {
			name : '♥ 10',
			north : {text:'value north hearts 10'},
			west : {text:'value west hearts 10'},
			station : {text:'value station hearts 10'},
			east : {text:'value east hearts 10'},
			south : {text:'value south hearts 10'},
		},
		'11' : {
			name : '♥ J 11',
			north : {text:'value north hearts J 11'},
			west : {text:'value west hearts J 11'},
			station : {text:'value station hearts J 11'},
			east : {text:'value east hearts J 11'},
			south : {text:'value south hearts J 11'},
		},
		'12' : {
			name : '♥ Q 12',
			north : {text:'value north hearts Q 12'},
			west : {text:'value west hearts Q 12'},
			station : {text:'value station hearts Q 12'},
			east : {text:'value east hearts Q 12'},
			south : {text:'value south hearts Q 12'},
		},
		'13' : {
			name : '♥ K 13',
			north : {text:'value north hearts K 13'},
			west : {text:'value west hearts K 13'},
			station : {text:'value station hearts K 13'},
			east : {text:'value east hearts K 13'},
			south : {text:'value south hearts K 13'},
		}
	},
	spades : {
		'1' : {
			name : '♠ 1',
			north : {text:'value north spades 1'},
			west : {text:'value west spades 1'},
			station : {text:'value station spades 1'},
			east : {text:'value east spades 1'},
			south : {text:'value south spades 1'},
		},
		'2' : {
			name : '♠ 2',
			north : {text:'value north spades 2'},
			west : {text:'value west spades 2'},
			station : {text:'value station spades 2'},
			east : {text:'value east spades 2'},
			south : {text:'value south spades 2'},
		},
		'3' : {
			name : '♠ 3',
			north : {text:'value north spades 3'},
			west : {text:'value west spades 3'},
			station : {text:'value station spades 3'},
			east : {text:'value east spades 3'},
			south : {text:'value south spades 3'},
		},
		'4' : {
			name : '♠ 4',
			north : {text:'value north spades 4'},
			west : {text:'value west spades 4'},
			station : {text:'value station spades 4'},
			east : {text:'value east spades 4'},
			south : {text:'value south spades 4'},
		},
		'5' : {
			name : '♠ 5',
			north : {text:'value north spades 5'},
			west : {text:'value west spades 5'},
			station : {text:'value station spades 5'},
			east : {text:'value east spades 5'},
			south : {text:'value south spades 5'},
		},
		'6' : {
			name : '♠ 6',
			north : {text:'value north spades 6'},
			west : {text:'value west spades 6'},
			station : {text:'value station spades 6'},
			east : {text:'value east spades 6'},
			south : {text:'value south spades 6'},
		},
		'7' : {
			name : '♠ 7',
			north : {text:'value north spades 7'},
			west : {text:'value west spades 7'},
			station : {text:'value station spades 7'},
			east : {text:'value east spades 7'},
			south : {text:'value south spades 7'},
		},
		'8' : {
			name : '♠ 8',
			north : {text:'value north spades 8'},
			west : {text:'value west spades 8'},
			station : {text:'value station spades 8'},
			east : {text:'value east spades 8'},
			south : {text:'value south spades 8'},
		},
		'9' : {
			name : '♠ 9',
			north : {text:'value north spades 9'},
			west : {text:'value west spades 9'},
			station : {text:'value station spades 9'},
			east : {text:'value east spades 9'},
			south : {text:'value south spades 9'},
		},
		'10' : {
			name : '♠ 10',
			north : {text:'value north spades 10'},
			west : {text:'value west spades 10'},
			station : {text:'value station spades 10'},
			east : {text:'value east spades 10'},
			south : {text:'value south spades 10'},
		},
		'11' : {
			name : '♠ J 11',
			north : {text:'value north spades J 11'},
			west : {text:'value west spades J 11'},
			station : {text:'value station spades J 11'},
			east : {text:'value east spades J 11'},
			south : {text:'value south spades J 11'},
		},
		'12' : {
			name : '♠ Q 12',
			north : {text:'value north spades Q 12'},
			west : {text:'value west spades Q 12'},
			station : {text:'value station spades Q 12'},
			east : {text:'value east spades Q 12'},
			south : {text:'value south spades Q 12'},
		},
		'13' : {
			name : '♠ K 13',
			north : {text:'value north spades K 13'},
			west : {text:'value west spades K 13'},
			station : {text:'value station spades K 13'},
			east : {text:'value east spades K 13'},
			south : {text:'value south spades K 13'},
		}
	},
	jockers : {
		'14' : {
			name : 'jockers R 14',
			north : {text:'value north jockers R 14'},
			west : {text:'value west jockers R 14'},
			station : {text:'value station jockers R 14'},
			east : {text:'value east jockers R 14'},
			south : {text:'value south jockers R 14'},
		},
		'0' : {
			name : 'jockers B 0',
			north : {text:'value north jockers B 0'},
			west : {text:'value west jockers B 0'},
			station : {text:'station value jockers B 0 Bad things happen!'},
			east : {text:'value east jockers B 0'},
			south : {text:'value south jockers B 0'},
		},
	}
}
